### ISSUE TITLE
Unable to cast object of type 'Hangfire.Couchbase.CouchbaseWriteOnlyTransaction' to type 'Hangfire.Storage.JobStorageTransaction'.

### ISSUE THREAD

**Issue by bbollard** [imranmomin/Hangfire.Couchbase#9]
Encountering this issue with Hangfire.Couchbase against our v4.6 Couchbase Server using 1.0.2 of Hangfire.Couchbase:

System.InvalidCastException: Unable to cast object of type 'Hangfire.Couchbase.CouchbaseWriteOnlyTransaction' to type 'Hangfire.Storage.JobStorageTransaction'.
   at Hangfire.Console.States.ConsoleApplyStateFilter.OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
   at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)
   at Hangfire.Server.Worker.TryChangeState(BackgroundProcessContext context, IStorageConnection connection, IFetchedJob fetchedJob, IState state, String[] expectedStates, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)

Any help would be appreciated.

Thanks!

**Comment by imranmomin** [comment]
@bbollard 
It is actually failing at Hangfire.Console

https://github.com/pieceofsummer/Hangfire.Console/blob/39d728ff7934206b1ca7d4dbab4c90c591c97c62/src/Hangfire.Console/States/ConsoleApplyStateFilter.cs#L36

**Comment by bbollard** [comment]
Ah, you are correct, thanks for the quick reply. I'll shoot over to that project.

**Comment by bbollard** [comment]
Looks like a similar issue with another storage provider:

https://github.com/pieceofsummer/Hangfire.Console/issues/17

**Comment by bbollard** [comment]
The console author states basically the same thing you are saying:

https://github.com/pieceofsummer/Hangfire.Console/issues/68#issuecomment-409712848

**Comment by imranmomin** [comment]
Funny, will put some time to implement the `JobStorageTransaction` abstract class. Will let you once done.. 

I will need your help to do testing.

**Comment by bbollard** [comment]
No problem, glad to help.

**Comment by imranmomin** [comment]
@bbollard can you test the branch with you project

https://github.com/imranmomin/Hangfire.Couchbase/commits/develop-9

**Comment by imranmomin** [comment]
@bbollard i have released the feature to support Hangfire.Console

https://github.com/imranmomin/Hangfire.Couchbase/releases/tag/1.1.0
